name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/Sunja-An/c0c9266e52496338a0cc0b0ec2a6713b.js }}
          TIMEZONE: Asia/Seoul
